#$schema: "http://json-schema.org/draft-07/schema"
#$id: "http://example.com/archilens.schema.json"
title: "Archilens"
description: "Architecture description schema"
$defs:
  flags:
    title: Flags
    type: object
    properties:
      soft_exclude_deep:
        type: boolean
    additionalItems: false
  tags:
    title: Flags
    type: array
    items:
      type: string
  zone:
    title: Zone
    description: "The unique identifier for a product"
    type: object
    properties:
      uid:
        type: string
      name:
        type: string
      domains:
        type: array
        items:
          $ref: "#/$defs/domain"
      flags:
        $ref: "#/$defs/flags"
      tags:
        $ref: "#/$defs/tags"
    required: [ uid ]
    additionalItems: false
  domain:
    title: Domain
    type: object
    properties:
      uid:
        type: string
      name:
        type: string
      entities:
        type: array
        items:
          $ref: "#/$defs/entity"
      flags:
        $ref: "#/$defs/flags"
      tags:
        $ref: "#/$defs/tags"
    required: [ uid ]
    additionalItems: false
  entity:
    oneOf:
      - $ref: "#/$defs/module"
      - $ref: "#/$defs/component"
      - $ref: "#/$defs/externalmodule"
  module:
    type: object
    properties:
      uid:
        type: string
      name:
        type: string
      components:
        type: array
        items:
          $ref: "#/$defs/component"
      api:
        oneOf:
          - type: boolean
          - type: string
      resources:
        type: array
        items:
          $ref: "#/$defs/resource"
      flags:
        $ref: "#/$defs/flags"
      tags:
        $ref: "#/$defs/tags"
    required: [ uid, components ]
    additionalItems: false
  component:
    type: object
    properties:
      uid:
        type: string
      ctype:
        type: string
      name:
        type: string
      relations:
        type: array
        items:
          $ref: "#/$defs/relation"
      flags:
        $ref: "#/$defs/flags"
      tags:
        $ref: "#/$defs/tags"
    required: [ uid, ctype ]
    additionalItems: false
  externalmodule:
    type: object
    properties:
      uid:
        type: string
      mtype:
        type: string
        enum: [ "App", "External", "Legacy", "Platform" ]
      name:
        type: string
      relations:
        type: array
        items:
          $ref: "#/$defs/relation"
      flags:
        $ref: "#/$defs/flags"
      tags:
        $ref: "#/$defs/tags"
    required: [ uid, mtype ]
    additionalItems: false
  resource:
    type: object
    properties:
      uid:
        type: string
      name:
        type: string
    required: [ uid ]
    additionalItems: false
  relation:
    type: object
    properties:
      target:
        type: string
      rtype:
        type: string
        enum: [ "Ask", "Listen", "Tell" ]
      reverse:
        type: boolean
      description:
        type: string
    required: [ target ]
    additionalItems: false
type: object
properties:
  ctypes:
    description: "The allowed component types"
    type: array
    items:
      - type: string
  zones:
    type: array
    items:
      $ref: "#/$defs/zone"
required: [ ctypes, zones ]
additionalItems: false
