input:
  pages:
    projects:   "f637565d1f79af72b17197f401d7d5ac"
    modules:    "3404483eaa991f0266ef50a9037a7196"
    components: "812533afe00ed00bf92d59d06a51221e"
    relations:  "056ed8c35bd3ea89f5bba998d43eb6f0"
    apis:       "f6ccaf0accb4ad075a38bf662926d4d8"
    resources:  "59bca60a5844088dcff948e58df3db6b"
diagrams:
  - output: 'output/plantuml/all-modules.plantuml'
    level: Module
    reverseRelationTypes: ['Ask', 'Tell', 'Listen']
  - output: 'output/plantuml/all-components.plantuml'
    level: Component
  - output: 'output/plantuml/all-api.plantuml'
    type: Api
    level: Module
  - output: 'output/plantuml/all-resource.plantuml'
    type: Api
    level: Component

  - output: 'output/plantuml/MyProject-module.plantuml'
    focusTags: ['MyProject']
    reverseRelationTypes: ['Ask', 'Tell', 'Listen']
  - output: 'output/plantuml/MyProject-components.plantuml'
    openTags: ['MyProject']
    relationLevel: Component
    reverseRelationTypes: ['Ask', 'Tell', 'Listen']
